### ISSUE TITLE
Unable to build Laravel Elixir assets in CI

### ISSUE THREAD

**Issue by bkuhl** [realpage/laravel-starter#29]
Laravel Elixir assets can't be built in the CI environment and must be committed to version control in order for php-fpm and nginx to be looking for the same version of the assets.  This happens because when `gulp` is run within CI there's a local file that assigns a unique hash to the version of each file.

One potential solution might be for the nginx/fpm Dockerfiles to use the commit hash as the random hash rather than assigning a fully unique one.

**Comment by jlaswell** [comment]
https://github.com/realpage-property-os/rentjoy/pull/55 has a solution here.

We've reverted to debian and added node via a build directly copied from the official library for node.

**Comment by bkuhl** [comment]
I wasn't clear enough in the original post here that the underlying issue is fpm/nginx not using the same hash.

**Comment by bkuhl** [comment]
Closing since elixir is no longer a thing.  I'd recommend https://github.com/bkuhl/laravel-fpm-nginx if you're looking for a container that can build front-end assets.
