### ISSUE TITLE
docker-compose up - Failed to open stream: Permission Denied

### ISSUE THREAD

**Issue by uiarch** [realpage/laravel-starter#56]
Hey guys I was playing with the Laravel starter this evening and ran into an issue. I got a permission denied error "**file_put_contents(/var/www/html/storage/framework/views/b18d705f49d4cb87cb2bde363b3ca5bd2bbb5823.php): failed to open stream: Permission denied**" after running docker-compose build then docker-compose up -d.

I was able to get passed this issue running a command to change permissions "**docker exec -it $(docker ps -f name=fpm -q) chmod -R 777 /var/www/html/storage/framework/views**" to said directory, but I do not feel confident that this is a good permanent fix. So I guess my question is what did I do wrong to make this issue happen in the first place? I did not do any configuration other than copying the env.sample to env, other than that I just ran the commands listed.

@bkuhl 

**docker -v** 
Docker version 1.12.2, build bb80604

**docker-machine -v**
docker-machine version 0.6.0, build e27fb87

**docker exec -it $(docker ps -f name=fpm -q) ls -latr**

Output:
total 2072
-rw-r--r--    1 1000     1000           813 Oct 12 01:12 stylelint.config.js
drwxr-xr-x    5 1000     1000          4096 Oct 12 01:12 storage
-rw-r--r--    1 1000     1000           563 Oct 12 01:12 server.php
drwxr-xr-x    5 1000     1000          4096 Oct 12 01:12 resources
drwxr-xr-x    3 1000     1000          4096 Oct 12 01:12 public
-rw-r--r--    1 1000     1000          1048 Oct 12 01:12 phpunit.xml
-rw-r--r--    1 1000     1000           400 Oct 12 01:12 package.json
drwxr-xr-x    6 1000     1000          4096 Oct 12 01:12 infrastructure
-rw-r--r--    1 1000     1000           556 Oct 12 01:12 gulpfile.js
drwxr-xr-x    5 1000     1000          4096 Oct 12 01:12 database
drwxr-xr-x    2 1000     1000          4096 Oct 12 01:12 config
-rw-r--r--    1 1000     1000          1328 Oct 12 01:12 composer.json
drwxr-xr-x    3 1000     1000          4096 Oct 12 01:12 bootstrap
-rwxr-xr-x    1 1000     1000          1646 Oct 12 01:12 artisan
-rw-r--r--    1 1000     1000          2377 Oct 12 01:12 CONTRIBUTING.md
-rw-r--r--    1 1000     1000          2670 Oct 12 01:12 .travis.yml
-rw-r--r--    1 1000     1000            61 Oct 12 01:12 .gitattributes
-rw-r--r--    1 1000     1000           357 Oct 12 01:12 .env.example
-rw-r--r--    1 1000     1000             9 Oct 12 01:12 .dockerignore
-rwxr-xr-x    1 1000     1000       1704783 Oct 12 01:55 composer.phar
drwxr-xr-x   32 1000     1000          4096 Oct 12 02:12 vendor
-rw-r--r--    1 1000     1000           357 Oct 20 00:57 .env
drwxr-xr-x    4 1000     1000          4096 Oct 20 00:59 tests
-rw-r--r--    1 1000     1000           633 Oct 20 00:59 docker-compose.yml
-rw-r--r--    1 1000     1000        127223 Oct 20 00:59 composer.lock
drwxr-xr-x    6 1000     1000          4096 Oct 20 00:59 app
-rw-r--r--    1 1000     1000            97 Oct 20 00:59 .gitignore
drwxr-xr-x    7 root     root          4096 Oct 20 01:00 ..
drwxr-xr-x    2 1000     1000          4096 Oct 20 01:52 routes
-rw-r--r--    1 1000     1000             1 Oct 20 02:13 README_DEFAULT.md
-rw-r--r--    1 1000     1000           263 Oct 20 02:34 README.md
drwxr-xr-x   14 1000     1000          4096 Oct 20 02:57 .
drwxr-xr-x    8 1000     1000          4096 Oct 21 02:08 .git

**Comment by bkuhl** [comment]
What's happening here is that the local Docker you're running is mounting the files as user `1000:1000` instead of `www-data` as we'd expect them to be.  Are you using Docker for mac and/or windows?  I'm using Docker for mac and my docker-machine version seems a bit more up to date:

```
➜  ~ docker -v
Docker version 1.12.1, build 6f9534c
➜  ~ docker-machine -v
docker-machine version 0.8.1, build 41b3b25
```

We can tell you how to fix this, but understanding what's driving your `docker-machine` version may impact the solution.

**Comment by grassroot2013** [comment]
I am running docker on Linux Mint 18 so maybe this is why my version is a little older?

**Comment by bkuhl** [comment]
How did you install docker?

**Comment by grassroot2013** [comment]
I used this tutorial here for docker. I will have to search a little to remember how I installed docker machine.

https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04

**Comment by grassroot2013** [comment]
Okay, finally I was able to get docker-machine updated on Linux Mint:

cd /usr/local/bin/
sudo wget https://github.com/docker/machine/releases/download/v0.8.2/docker-machine-$(uname -s)-$(uname -m)

sudo mv docker-machine-Linux-x86_64 docker-machine

sudo chmod +x docker-machine

I followed the same steps with docker-compose to update it to the latest version as well, re-ran build and up and then everything was working fine.

So I guess it was just a version issue, and for the record it was not this hard on my mac. I think this can be resolved. Thanks!

**Comment by bkuhl** [comment]
Glad to know you have it resolved.  We use Docker for mac and our understanding is that Docker for mac/windows solves the issue with mounted files showing up as being owned by `1000:1000` instead of `www-data:www-data`

**Comment by 2n2n** [comment]
@bkuhl I'm having the same issue how did you fix this?

**Comment by rubinchyk** [comment]
The same problem.

**Comment by bkuhl** [comment]
I'd recommend using https://github.com/bkuhl/laravel-starter over this one.  This one includes the Laravel project out of the gate which is almost never up to date.
