### ISSUE TITLE
Loading from cache - composer

### ISSUE THREAD

**Issue by uiarch** [realpage/laravel-starter#57]
When I clone my repo into another directory and run docker-compose build I get "Loading from cache" for the composer commands and it does not create my vendor directory. I erased all my code started a new repo and re-clone this one and got the same thing. What did I do wrong? I wouldn't think that my local composer would need to clear the cache since this build should do that or something like that.

**Comment by mh3720** [comment]
Realpage/laravel-starter has been broken for a long time. We are in the process of replacing it.
For now, just run composer install in the fpm container afterwards. 

-------- Original message --------

**Comment by bkuhl** [comment]
Can you provide the exact commands you're running and the CLI output?

We've used the starter on several projects and have not experienced this issue.

**Comment by bkuhl** [comment]
Closing this out due to lack of response.
