### ISSUE TITLE
how to run this in production? 

### ISSUE THREAD

**Issue by g0ld3lux** [realpage/laravel-starter#66]
Hi i only see local deployment, but what about if i want to deploy in Digital Ocean or Amazon...

can you give me more info thanks

**Comment by bkuhl** [comment]
The recommended approach is to use [travis-ci to build docker containers](https://github.com/realpage/laravel-starter/blob/master/.travis.yml#L21) and then ship those to production.  Alternatively, you could just use Docker for local development and in production use a deployment tool like [Rocketeer](http://rocketeer.autopergamene.eu/) or [Deployer](https://deployer.org)

**Comment by bkuhl** [comment]
If you do want to deploy with Docker in DO or AWS, we recommend using [Rancher ](http://rancher.com/).  The starter comes with [example configuration and instructions](https://github.com/realpage/laravel-starter/tree/master/infrastructure/rancher-example) on how to set it up.
